version: '3'

services:
    nginx:
        container_name: nginx
        volumes:
        - wordpress:/var/www/wordpress
        networks:
        - inception
        depends_on:
        - wordpress
        build:
            context: requirements/nginx
        image: nginx
        env_file: .env
        ports:
        - "443:443"
        restart: on-failure

    mariadb:
        container_name: mariadb
        networks:
        - inception
        build:
            context: requirements/mariadb
        image: mariadb
        env_file: .env
        volumes:
        - mariadb:/var/lib/mysql
        restart: unless-stopped
        expose:
        - "3306"

    wordpress:
        container_name: wordpress
        env_file: .env
        volumes:
        - wordpress:/var/www/wordpress
        networks:
        - inception
        build:
            context: requirements/wordpress
        image: wordpress
        depends_on:
        - mariadb
        restart: on-failure
        expose:
        - "9000"

volumes:
    wordpress:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: '/home/gt-serst/data/wordpress'
    mariadb:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: '/home/gt-serst/data/mariadb'

networks:
    inception:
        driver: bridge
