version: '3'
services:
  wordpress:
    build:
      context: .
      args:
        - MYWP_DATABASE
        - MYWP_USER
        - MYWP_PASSWORD
        - MYWP_URL
        - MYWP_ADMIN_USER
        - MYWP_ADMIN_PASSWORD
        - MYWP_ADMIN_EMAIL
        - MYWP_EMAIL
        - MYWP_SUB_USER
        - MYWP_SUB_EMAIL
        - MYWP_SUB_ROLE
        - MYWP_SUB_PASSWORD
      dockerfile: Dockerfile
    container_name: wordpress
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/test/data/wordpress'
