services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/mysql
    restart: always

volumes:
  db_volume: {}
